version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Tricapic
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"

  springbootapp:
    build: ./tricapic
    ports:
      - "8081:8080"
    command: java -jar /tricapic/target/demo-0.0.1-SNAPSHOT.jar
    depends_on:
      - mariadb